### config.toml
title = "CfgMgmtCamp"
baseURL = "https://cfgmgmtcamp.eu/"
theme = "cfgmgmtcamp"
languageCode = "ghent2021"
defaultContentLanguage = "ghent2021"
defaultContentLanguageInSubdir = true
enableMissingTranslationPlaceholders = true
dataDir = "data"
assetDir = "assets"
PaginatePath = "blog"
sectionPagesMenu = "main"
buildDrafts = false
pygmentsUseClasses = true
enableGitInfo = true
enableRobotsTXT = true

[outputs]
	section = [ "HTML", "Calendar", "RSS" ]

[outputFormats]
[outputFormats.RSS]
	mediatype = "application/rss"
	baseName = "feed"
	suffix = "xml"
