
[ghent2023]
	title = "CfgMgmtCamp 2023"
	contentDir = "content/ghent2023/"
	weight = -2022
[ghent2022]
	title = "CfgMgmtCamp 2022"
	contentDir = "content/ghent2022/"
	weight = -2022
[ghent2021]
	title = "CfgMgmtCamp 2021"
	contentDir = "content/ghent2021/"
	weight = -2021
[ghent2020]
	title = "CfgMgmtCamp 2020"
	contentDir = "content/ghent2020/"
	weight = -2020
[ghent2019]
	title = "CfgMgmtCamp 2019"
	contentDir = "content/ghent2019/"
	weight = -2019
