### navbar
[[navbar]]
	name = "About"
	identifier = "about"
	url = "/ghent2024/about/"
	weight = -1000
[[navbar]]
	name = "Registration"
	identifier = "registration"
	url = "/ghent2024/registration/"
	weight = -900
#[[navbar]]
#	name = "FOSDEM"
#	identifier = "registration"
#	url = "https://fosdem.org/2023/schedule/track/infra_management/"
#	#url = "https://registration.cfgmgmtcamp.be/ghent/2023/"
#	weight = -900
[[navbar]]
	name = "CfP"
	identifier = "cfp"
	url = "https://cfp.cfgmgmtcamp.org/2024/cfp"
	weight = -800
[[navbar]]
	name = "Sponsors"
	identifier = "sponsors"
	url = "/ghent2024/sponsors/"
	weight = -700
#[[navbar]]
#	name = "Schedule"
#	identifier = "schedule"
#	url = "/ghent2024/schedule/"
#	weight = -600
#[[navbar]]
#	name = "Fringe"
#	identifier = "fringes"
#	url = "/ghent2024/fringes/"
#	weight = -400
#[[navbar]]
#	name = "Speakers"
#	identifier = "speakers"
#	url = "/ghent2024/speaker/"
#	weight = -350
[[navbar]]
	name = "Location"
	identifier = "location"
	url = "/ghent2024/location/"
	weight = -500
[[navbar]]
	name = "Conduct"
	identifier = "conduct"
	url = "/ghent2024/codeofconduct/"
	weight = -300
[[navbar]]
	name = "Past"
	identifier = "past"
	url = "/ghent2024/past/"
	#url = "https://archive.cfgmgmtcamp.eu/"
	weight = -100
