### config.toml
title = "CfgMgmtCamp"
baseURL = "https://cfgmgmtcamp.eu/"
theme = "cfgmgmtcamp"
languageCode = "en-us"
dataDir = "data"
assetDir = "assets"
PaginatePath = "blog"
sectionPagesMenu = "main"
buildDrafts = false
pygmentsUseClasses = true
enableGitInfo = true
enableRobotsTXT = true

[outputs]
section = [ "HTML", "Calendar" ]

### navbar
[[menu.navbar]]
	name = "About"
	identifier = "about"
	url = "/about/"
	weight = -1000
[[menu.navbar]]
	name = "Registration"
	identifier = "registration"
	url = "https://registration.cfgmgmtcamp.be/ghent/2019/"
	weight = -900
[[menu.navbar]]
	name = "Sponsors"
	identifier = "sponsors"
	url = "/sponsors/"
	weight = -800
[[menu.navbar]]
	name = "Location"
	identifier = "location"
	url = "/location/"
	weight = -700
[[menu.navbar]]
	name = "CfP"
	identifier = "cfp"
	url = "https://cfp.cfgmgmtcamp.be"
	weight = -600
#[[menu.navbar]]
#	name = "Schedule"
#	identifier = "schedule"
#	url = "/schedule/"
#	weight = -600
[[menu.navbar]]
	name = "Fringe"
	identifier = "fringes"
	url = "/fringes/"
	weight = -400
[[menu.navbar]]
	name = "Conduct"
	identifier = "conduct"
	url = "/codeofconduct/"
	weight = -300
[[menu.navbar]]
	name = "Archive"
	identifier = "archive"
	url = "https://archive.cfgmgmtcamp.eu/"
	weight = -100

[params.analytics.piwik]
	URL = "https://stats.vantosh.com"
	ID = "45"

